### ISSUE TITLE
关于右下角3个tab按钮点击问题

### ISSUE THREAD

**Issue by fhefh2015** [appbone/mobile-spa-boilerplate#1]
点击tab上的任一个按钮 tab框也进行动画了 感觉体验不好

**Comment by ufologist** [comment]
猜想你看的是基于 SUI Mobile 实现的版本, 他目前的版本 `v0.6.2` 不支持禁用路由动画, 不过源码在那里, 修改起来不难实现.

但由于我主要是想基于官方的版本来做, 因此没有实现这个功能了.

对于这个问题, 在我的基于 Framework7 实现的版本中解决了, 你可以参考这个版本.

PS
- https://github.com/appbone/mobile-spa-boilerplate 是基于 SUI Mobile 实现的版本
- https://github.com/appbone/mobile-spa-boilerplate/tree/gh-pages 是基于 Framework7 实现的版本

非常感谢你的反馈.
